version: '2'
services: 
    web:
        build: .
        ports: 
        - "8888:80"
        environment:
        - PROXY_PATH=/dokku/baxreport/
        links:
        - redis
    redis:
        image: redis:alpine
